spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blps
    username: callmepedro
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true


application:
  security:
    jwt:
      secret: kvKHL5jkO4wrWWzyH+2fEhOnBp/a9nvwDD2XTE8GFmE=
      accessExpiresIn: 900
      refreshExpiresIn: 86400

